#!/bin/bash

set -e
# FIXME it's not adapted for electrum-crown
host=$1
version=`git describe --tags`
echo $version

here=$(dirname "$0")
cd $here/../dist

sftp -oBatchMode=no -b - thomasv@$host << !
   cd electrum-downloads
   mkdir $version
   cd $version
   mput *
   bye
!
