#!/usr/bin/env python3

from electrumcrown import set_verbosity
from electrumcrown.network import filter_version
import util, json
set_verbosity(False)

servers = filter_version(util.get_peers())
print(json.dumps(servers, sort_keys = True, indent = 4))
